Change groupId to org.wrensecurity.commons
WrenSecurity/wrensec-commons pull request #35
Opened 2022-04-01 20:50 UTC by kvcvc

Changed groupId to org.wrensecurity.commons. See #34.

2022-04-02 08:24 UTC, pavelhoral requested changes

2022-04-02 13:24 UTC, kvcvc commented on http-framework/CHANGELOG.md
> +# 22.2.2
No, will revert that.

2022-04-02 13:26 UTC, kvcvc commented on self-service/forgerock-selfservice-example/src/license/THIRD-PARTY.properties
> +org.wrensecurity.commons.ui.libs--backbone--1.1.2=123
You're right. org.forgerock.commons.ui is out of mentioned scope, will revert that.

2022-04-06 13:18 UTC, kvcvc commented on audit/forgerock-audit-benchmark/pom.xml
> +        <version>22.2.2-SNAPSHOT</version>
Indeed.

2022-04-06 14:01 UTC, merged